### ISSUE TITLE
Laravel 5.3 Support

### ISSUE THREAD

**Issue by simkepal** [LaravelCollective/iron-queue#16]
Hey!

Will it be possible to use this package with laravel 5.3? If not I have to find another solution.

Thank you!

Best regards!

**Comment by trideout** [comment]
Is anyone working on this?

**Comment by jaketoolson** [comment]
Is this package dead?

**Comment by jaketoolson** [comment]
Is this package dead?

**Comment by simkepal** [comment]
It would be great to know what is going on with this project....

**Comment by majksner** [comment]
There is already closed issue https://github.com/LaravelCollective/iron-queue/issues/15

But it seems nobody cares.

**Comment by drakakisgeo** [comment]
I'll make a pull request soon, it is working for me locally.

**Comment by simkepal** [comment]
Ufff, that would be great! Or if you make your repo public :)

**Comment by drakakisgeo** [comment]
The reason I don't make a PR is because some tests fail. You can check the code in my fork https://github.com/drakakisgeo/iron-queue and the changes here -> https://github.com/LaravelCollective/iron-queue/compare/5.2...drakakisgeo:dev-5.3?expand=1

**Comment by majksner** [comment]
Size method using wrong code copied from SQS queue implementation:

https://github.com/LaravelCollective/iron-queue/compare/5.2...drakakisgeo:dev-5.3?expand=1#diff-3ccff2f8587d87d30ba6844ecb1141dfR296

Use this instead:
```php
public function size($queue = null)
{
    return 0;
}
```

**Comment by drakakisgeo** [comment]
Replaced that @majksner , thanks!

**Comment by jaketoolson** [comment]
It would just be great if we could have some more contributors authorized to approve PR's etc to keep this going.  

Iron.io and Push queues are very under-appreciated.  I would hate to see this package continue to remain unmaintained.

**Comment by golonix** [comment]
It seems like original authors/maintainers ditched this package. I've decided to fork it and maintain it on my own. I've also added L5.3 support. You can find it here: https://github.com/HydrefLab/iron-queue

Feel free to use it. All contributions are most welcome :)

**Comment by trideout** [comment]
The L5.3 support has been merged into the new branch 5.3 and is now tagged for composer
