### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by trideout** [LaravelCollective/iron-queue#21]
I am bringing support for this package up to date. If anyone would like to submit a PR for 5.4 support I would be great full, otherwise I should be able to bring support up to date within the week.

**Comment by HammamSamara** [comment]
I am wondering if this is done or anything since I did a fork weeks ago to resolve it.
If it is an issue, please consider my attempt at: https://github.com/LaravelCollective/iron-queue/compare/5.4...Yamsafer:dev-5.4

**Comment by trideout** [comment]
Yes, 5.4 support is complete and available on the releases page
