### ISSUE TITLE
Iron MQ Upgrade (v2 => v3)

### ISSUE THREAD

**Issue by dennisoderwald** [LaravelCollective/iron-queue#6]
http://www.iron.io/blog/2014/06/ironmq-enterprise-powered-by-ironmq-v3.html

**Comment by majksner** [comment]
+1

**Comment by drekinov** [comment]
+1
at least @LaravelCollective could confirm if they will review pull request if they do not have time to upgrade it

there is fork from @minutemailer with some V3 commits but it is not confirmed if it is working implementation or half-done

**Comment by carvefx** [comment]
+1 any news on this?

**Comment by ivannovak** [comment]
+1

**Comment by carvefx** [comment]
there is currently a PR open [https://github.com/LaravelCollective/iron-queue/pull/9] that looks promising. just a style issue to sort out and it should be ready to merge.

**Comment by tshafer** [comment]
Im out of office but will be back soon and will take a look. From first glance it looks good.

— 
Tom Shafer

**Comment by tshafer** [comment]
Done
