### ISSUE TITLE
Upgrading to a newer API is now a requirement for this package

### ISSUE THREAD

**Issue by robclancy** [LaravelCollective/iron-queue#7]
When new to iron.io you can't use their old API. This means this package doesn't work because of https://github.com/laravel/framework/issues/10828.

Anyone on older versions of the API would have had the option to stay on it. But new users do not, this must be why you haven't had this request here yet.

I am on 5.1 LTS which also has this issue and going to just put the changes in https://github.com/laravel/framework/pull/11084 back in and deal with issues as they come up. If I find a proper solution I will make a PR.

---

_if they allow some way to be a new user and use the old API then please show me and I can edit out the requirement part_

**Comment by dennisoderwald** [comment]
+1

**Comment by tshafer** [comment]
Done
